spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: prod

logging:
  level:
    root: info
server:
  port: 8080
  servlet:
    context-path: /

  error:
    whitelabel:
      enabled: false
management:
  endpoints:
    health:
      group:
        custom:
          show-components: always
    web:
      exposure:
        include: all
#  management.endpoint.health.group.custom.show-details=always
info:
  app:
    name: Online Shop
    author:
      name: Dodangeh
  company:
    location: Tehran


--- #Prod

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
logging:
  level:
    root: info

user:
  name:
    custom : x
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: debug